import type { Metadata } from "next";
import { Sora } from "next/font/google";
import { Footer } from "./_components/Footer";
import "./globals.css";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} antialiased max-w-3xl mx-auto w-full min-h-screen`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
