import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../components/main/Navbar";
import { ThemeProvider } from "next-themes"
import { Providers } from "./providers"
import "./globals.css";

export interface ColorMode{
  font: string,
  bg: string
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className} flex justify-center`}>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </body>
    </html>
  );
}
